"""insert

Revision ID: 4b623fb01876
Revises: 6f56c857363e
Create Date: 2023-02-12 17:59:22.172288

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b623fb01876'
down_revision = '6f56c857363e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
