"""insert data in cart

Revision ID: 7d6b97e5d46b
Revises: 5cc471fb493e
Create Date: 2023-02-11 13:10:16.069966

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6b97e5d46b'
down_revision = '5cc471fb493e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product_name', sa.String(length=100), nullable=True))
    op.add_column('cart', sa.Column('product_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'product_price')
    op.drop_column('cart', 'product_name')
    # ### end Alembic commands ###
